# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
source $HOME/dotfiles/system/theme

# Plugins
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	command-not-found
)
# oh-my-zsh initalization
source $ZSH/oh-my-zsh.sh

# Auto Completion
source $HOME/dotfiles/system/autocomplete

# Options
source $HOME/dotfiles/system/options

# Editor Choice
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi

if [[ -e $HOME/dotfiles/system/alias ]]; then
	source $HOME/dotfiles/system/alias
fi

if [[ -e $HOME/dotfiles/system/functions ]];then
	source $HOME/dotfiles/system/functions
fi

if [[ -e $HOME/dotfiles/system/binds ]]; then
	source $HOME/dotfiles/system/binds
fi

# Fixes gpg prompts
export GPG_TTY=$(tty)

# Rust variables
if [[ -e $HOME/.cargo/env ]]; then
	source "$HOME/.cargo/env"
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
