# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
source $HOME/dotfiles/system/theme

# Plugins
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	command-not-found
)
# oh-my-zsh initalization
source $ZSH/oh-my-zsh.sh

# Auto Completion
source $HOME/dotfiles/system/autocomplete

# Options
source $HOME/dotfiles/system/options

# Editor Choice
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi

if [[ -e $HOME/dotfiles/system/alias ]]; then
	source $HOME/dotfiles/system/alias
fi

if [[ -e $HOME/dotfiles/system/functions ]];then
	source $HOME/dotfiles/system/functions
fi

if [[ -e $HOME/dotfiles/system/binds ]]; then
	source $HOME/dotfiles/system/binds
fi

if [[ -e $HOME/dotfiles/system/local_exports ]]; then
	source $HOME/dotfiles/system/local_exports
fi

# Fixes gpg prompts
export GPG_TTY=$(tty)
