#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 2; done
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
  done
else
  polybar --reload example &
fi
light-locker &
blueman-applet &
nm-applet &
udiskie -s &



INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI1"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then 
	  bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
	  bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 ♫
  	bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
		 else
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 ♫
	fi

bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
	
bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"


bspc rule -a Blueman-manager state=floating center=on

feh --bg-center ~/Pictures/Found-Kitten-0-8-Weeks-Busy-scaled.jpg

