#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
killall -q nm-applet
killall -q light-locker
killall -q udiskie
killall -q blueman-applet
killall -q polybar
killall -q picom
killall -q batsignal
while pgrep -u $UID -x polybar > /dev/null; do sleep 2; done
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload $(cat /etc/hostname) &
  done
else
	polybar --reload $(cat /etc/hostname) &
fi
light-locker &
blueman-applet &
nm-applet &
udiskie -s &
picom &
batsignal -p


INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"

if [[ -e $HOME/dotfiles/.config ]]; then
		source $HOME/dotfiles/.config
fi

echo "$INTERNAL_MONITOR"

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then 
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
	bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 ♫
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
	elif [[ $(xrandr -q | grep "${INTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 ♫
	else
		bspc monitor -d 1 2 3 4 5 6 7 8 9 ♫
fi

bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
	
bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"


bspc rule -a Blueman-manager state=floating center=on
bspc rule -a Zathura state=tiled
bspc rule -a Spotify desktop=♫ state=tiled focus=off

feh --bg-center ~/Pictures/Found-Kitten-0-8-Weeks-Busy-scaled.jpg

wmname LG3D
